# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
# https://docs.github.com/en/webhooks/webhook-events-and-payloads#repository_dispatch

# https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb

name: R Package Build from Trigger

on: 
  repository_dispatch:
    types: [build-r-package]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Checkout trigger repo
        uses: actions/checkout@v4
        with:
          repository: mhpob/demo-data
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ secrets.API_KEY }}
          path: 'demo-data'

      - name: List files in demo-data
        run: |
          cd demo-data
          find ~+/raw -type f | grep -v "yaml"

      - name: List files in r-package
        run: |
          cd ../demo-data-r-package
          ls

      - name: See differences?
        run: |
          cd "${{ github.workspace }}"
          git status
          
